version: "3"
services:
  app:
    build: backend
    volumes:
      - tmp:/tmp:rw
      - sock:/sock/:rw
    network_mode: none
    read_only: true
    security_opt:
      - no-new-privileges=true
    cap_drop: [all]
    init: true
    restart: always
  nginx:
    build: frontend
    ports:
      - 8080:80
    volumes:
      - sock:/sock/:ro
volumes:
  tmp: {}
  sock: {}
