version: "3"
services:
  app:
    build: backend
    volumes:
      - tmp:/tmp:rw
      - sock:/sock/:rw
    network_mode: none
    read_only: true
    security_opt:
      - no-new-privileges=true
    init: true
    restart: always
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - sock:/sock/:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
volumes:
  tmp: {}
  sock: {}
