version: "3"
services:
  backend:
    build: backend
    volumes:
      - tmp:/tmp:rw
      - sock:/sock/:rw
      - cache:/data/:rw
    network_mode: none
    read_only: true
    security_opt:
      - no-new-privileges=true
    cap_drop: [all]
    cap_add: [CAP_CHOWN, CAP_SETUID, CAP_SETGID]
    restart: always
  frontend:
    build: frontend
    ports:
      - 8080:8080
    cap_drop: [all]
    security_opt:
      - no-new-privileges=true
    volumes:
      - sock:/sock/:ro
      - cache:/usr/share/nginx/html/d/:ro
volumes:
  cache: {}
  tmp: {}
  sock: {}
